name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ${{ matrix.operating-system }}
    strategy:
      fail-fast: false
      matrix:
        operating-system: [ubuntu-latest, windows-latest, macOS-latest]
        dotnet-version: ['5.0.x']
    env:
      SOLUTION: "./source/Appccelerate.IO.sln"
    steps:
    - name: helper
      run: echo "SOLUTION . $SOLUTION"
    - uses: actions/checkout@v2
    - name: Setup .NET ${{ matrix.dotnet-version }}
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ matrix.dotnet-version }}
    - name: Restore dependencies
      run: dotnet restore $SOLUTION
    - name: Build
      run: dotnet build $SOLUTION --no-restore
    - name: Test
      run: dotnet test $SOLUTION --no-build --verbosity normal
